# Generated by Django 3.2.12 on 2022-03-02 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("processing_time", models.IntegerField()),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "New"), (2, "Processing"), (3, "Completed"), (4, "Error")], default=1
                    ),
                ),
            ],
        ),
    ]
